# 设置启动端口号
server:
  port: 8088
spring:
  # 配置Dubbo相关信息
  dubbo: 
    application: 
      name: xmall-server
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.augustars.xmall
  # 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmall
    username: root
    password: java
  # 配置动态代理为CGLIB
  aop:
    proxy-target-class: true
  # 配置JPA相关信息
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: true