server:
  port: 8089
spring:
  # 配置Dubbo相关信息
  dubbo: 
    application: 
      name: xmall-server
    registry: 
      address: zookeeper://127.0.0.1:2181
    protocol: 
      name: dubbo
      port: 20880
    scan: com.augustars.xmall